### ISSUE TITLE
Postman workspace : start using environments and environment variables

### ISSUE THREAD

**Issue by dirk-jacobs** [Hand-And-Paw/hand-and-paw#192]
https://www.tutorialspoint.com/postman/postman_environment_variables.htm

**Comment by rago89** [comment]
Hello Dirk, I create the environment variable, in this case with the new config that you created is always going to be in port 3000, but is more clean the board, and also is cool to know about it

**Comment by dirk-jacobs** [comment]
You forgot a few, I added them.

please add the Heroku environment

**Comment by rago89** [comment]
True

Le mar. 2 nov. 2021 à 7:09 PM, Dirk Jacobs ***@***.***> a
écrit :
